services:
  - type: web
    name: journal-bot-server-main
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: COHERE_API_KEY
        sync: false
    plan: free 