services:
  - type: web
    name: journal-bot-server-main
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CO_API_KEY
        sync: false
      - key: PORT
        value: 8080
    plan: free 